ERROR:__main__:2022-12-21 17:20:14,185:local variable 'portfolio_dict' referenced before assignment
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 128, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 705, in update
    self._get_situation()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 589, in _keep_a_check
    if (self.priceatri.yes_best_price < self.stop_buy_upper_price) and (self.priceatri.yes_best_price >= self.stop_buy_lower_price) :
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 267, in __scalp_side
    if (temp_qty > 0) and (temp_price <= self.stop_buy_upper_price) and (not self.order.is_same_order("Y", temp_price, temp_qty, "buy")) and (not self._is_myorder_best("Y")):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 426, in _is_myorder_best
    best_price = 0
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\order.py", line 170, in is_same_order
    df = self.mybet.get_event_holdings(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 44, in get_event_holdings
    port_dict = self._get_portfolio_dict()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 41, in _get_portfolio_dict
    return portfolio_dict
UnboundLocalError: local variable 'portfolio_dict' referenced before assignment
ERROR:__main__:2022-12-21 23:01:13,891:MaxAttempt(3) exhausted. User0
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 118, in tradex_caller
    response = req.post(url, data=body, headers=headers).json()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 128, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 705, in update
    self._get_situation()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 589, in _keep_a_check
    if (self.priceatri.yes_best_price < self.stop_buy_upper_price) and (self.priceatri.yes_best_price >= self.stop_buy_lower_price) :
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 271, in __scalp_side
    self.__send_buy_orders(f"{trigger},ScalpingYes,{set_priceqty_message}", "Y", temp_price, temp_qty)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 546, in __send_buy_orders
    return sell_price, sell_qty, message
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\order.py", line 38, in _buy
    response = self.api_obj.tradex_caller(suffix, body)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 140, in tradex_caller
    raise Exception(f"MaxAttempt({retry_attempts}) exhausted. User{self.userid}")
Exception: MaxAttempt(3) exhausted. User0
ERROR:__main__:2022-12-21 23:01:55,740:MaxAttempt(3) exhausted. User0
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 118, in tradex_caller
    response = req.post(url, data=body, headers=headers).json()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 128, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 705, in update
    self._get_situation()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 589, in _keep_a_check
    if (self.priceatri.yes_best_price < self.stop_buy_upper_price) and (self.priceatri.yes_best_price >= self.stop_buy_lower_price) :
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 271, in __scalp_side
    self.__send_buy_orders(f"{trigger},ScalpingYes,{set_priceqty_message}", "Y", temp_price, temp_qty)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 546, in __send_buy_orders
    return sell_price, sell_qty, message
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\order.py", line 38, in _buy
    response = self.api_obj.tradex_caller(suffix, body)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 140, in tradex_caller
    raise Exception(f"MaxAttempt({retry_attempts}) exhausted. User{self.userid}")
Exception: MaxAttempt(3) exhausted. User0
ERROR:__main__:2022-12-21 23:02:39,076:MaxAttempt(3) exhausted. User0
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 118, in tradex_caller
    response = req.post(url, data=body, headers=headers).json()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 128, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 705, in update
    self._get_situation()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 626, in _keep_a_check
    trigger = "HoldYesQtyChange"
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 351, in __hold_qty_change_process
    self.__send_all_sell(f"{trigger},SellingNoNewQty,{set_priceqty_message}", "N", sell_price, sell_qty)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 554, in __send_all_sell
    def __send_all_sell(self, message, asset, sell_price, sell_qty):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\order.py", line 71, in _sell
    response = self.api_obj.tradex_caller(suffix, body)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 140, in tradex_caller
    raise Exception(f"MaxAttempt({retry_attempts}) exhausted. User{self.userid}")
Exception: MaxAttempt(3) exhausted. User0
ERROR:__main__:2022-12-21 23:03:21,887:MaxAttempt(3) exhausted. User0
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 118, in tradex_caller
    response = req.post(url, data=body, headers=headers).json()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 128, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 705, in update
    self._get_situation()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 598, in _keep_a_check
    self.__scalp_side("Y", trigger, pausebuy=True, pausesell=False)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 304, in __scalp_side
    self.__send_buy_orders(f"{trigger},ScalpingNo,{set_priceqty_message}", "N", temp_price, temp_qty)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 548, in __send_buy_orders
    def __send_buy_orders(self, message, asset, price, qty):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\order.py", line 38, in _buy
    response = self.api_obj.tradex_caller(suffix, body)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 140, in tradex_caller
    raise Exception(f"MaxAttempt({retry_attempts}) exhausted. User{self.userid}")
Exception: MaxAttempt(3) exhausted. User0
ERROR:__main__:2022-12-21 23:04:04,861:MaxAttempt(3) exhausted. User0
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 118, in tradex_caller
    response = req.post(url, data=body, headers=headers).json()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 128, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 705, in update
    self._get_situation()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 598, in _keep_a_check
    self.__scalp_side("Y", trigger, pausebuy=True, pausesell=False)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 304, in __scalp_side
    self.__send_buy_orders(f"{trigger},ScalpingNo,{set_priceqty_message}", "N", temp_price, temp_qty)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 548, in __send_buy_orders
    def __send_buy_orders(self, message, asset, price, qty):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\order.py", line 38, in _buy
    response = self.api_obj.tradex_caller(suffix, body)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 140, in tradex_caller
    raise Exception(f"MaxAttempt({retry_attempts}) exhausted. User{self.userid}")
Exception: MaxAttempt(3) exhausted. User0
