ERROR:__main__:2022-11-16 15:36:07,414:cannot encode object: 76, of type: <class 'numpy.int64'>
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 114, in <module>
    strat_obj_dict[i].initialise()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 391, in initialise
    self._strat_status_record()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 134, in _strat_status_record
    self.stratRecorObj._add_one_doc(data_dict)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat_live_status_recorder.py", line 12, in _add_one_doc
    database.insert_dict("tradex_strat_data", f"strat{self.strategy_num}_{self.event_id}", data_dict)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\MongoClient.py", line 15, in insert_dict
    self.collection.insert_one(data_dictionary)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\collection.py", line 621, in insert_one
    self._insert_one(
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\collection.py", line 562, in _insert_one
    self.__database.client._retryable_write(acknowledged, _insert_command, session)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\mongo_client.py", line 1448, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\mongo_client.py", line 1321, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\_csot.py", line 105, in csot_wrapper
    return func(self, *args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\mongo_client.py", line 1362, in _retry_internal
    return func(session, sock_info, retryable)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\collection.py", line 550, in _insert_command
    result = sock_info.command(
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\pool.py", line 794, in command
    self._raise_connection_failure(error)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\pool.py", line 766, in command
    return command(
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\network.py", line 127, in command
    request_id, msg, size, max_doc_size = message._op_msg(
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\message.py", line 687, in _op_msg
    return _op_msg_uncompressed(flags, command, identifier, docs, opts)
bson.errors.InvalidDocument: cannot encode object: 76, of type: <class 'numpy.int64'>
ERROR:__main__:2022-11-16 15:36:16,434:cannot encode object: 76, of type: <class 'numpy.int64'>
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 114, in <module>
    strat_obj_dict[i].initialise()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 391, in initialise
    self._strat_status_record()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 134, in _strat_status_record
    self.stratRecorObj._add_one_doc(data_dict)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat_live_status_recorder.py", line 12, in _add_one_doc
    database.insert_dict("tradex_strat_data", f"strat{self.strategy_num}_{self.event_id}", data_dict)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\MongoClient.py", line 15, in insert_dict
    self.collection.insert_one(data_dictionary)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\collection.py", line 621, in insert_one
    self._insert_one(
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\collection.py", line 562, in _insert_one
    self.__database.client._retryable_write(acknowledged, _insert_command, session)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\mongo_client.py", line 1448, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\mongo_client.py", line 1321, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\_csot.py", line 105, in csot_wrapper
    return func(self, *args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\mongo_client.py", line 1362, in _retry_internal
    return func(session, sock_info, retryable)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\collection.py", line 550, in _insert_command
    result = sock_info.command(
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\pool.py", line 794, in command
    self._raise_connection_failure(error)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\pool.py", line 766, in command
    return command(
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\network.py", line 127, in command
    request_id, msg, size, max_doc_size = message._op_msg(
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\message.py", line 687, in _op_msg
    return _op_msg_uncompressed(flags, command, identifier, docs, opts)
bson.errors.InvalidDocument: cannot encode object: 76, of type: <class 'numpy.int64'>
ERROR:__main__:2022-11-16 15:36:39,582:cannot encode object: 24, of type: <class 'numpy.int64'>
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 114, in <module>
    strat_obj_dict[i].initialise()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 391, in initialise
    self._strat_status_record()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 134, in _strat_status_record
    self.stratRecorObj._add_one_doc(data_dict)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat_live_status_recorder.py", line 12, in _add_one_doc
    database.insert_dict("tradex_strat_data", f"strat{self.strategy_num}_{self.event_id}", data_dict)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\MongoClient.py", line 15, in insert_dict
    self.collection.insert_one(data_dictionary)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\collection.py", line 621, in insert_one
    self._insert_one(
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\collection.py", line 562, in _insert_one
    self.__database.client._retryable_write(acknowledged, _insert_command, session)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\mongo_client.py", line 1448, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\mongo_client.py", line 1321, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\_csot.py", line 105, in csot_wrapper
    return func(self, *args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\mongo_client.py", line 1362, in _retry_internal
    return func(session, sock_info, retryable)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\collection.py", line 550, in _insert_command
    result = sock_info.command(
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\pool.py", line 794, in command
    self._raise_connection_failure(error)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\pool.py", line 766, in command
    return command(
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\network.py", line 127, in command
    request_id, msg, size, max_doc_size = message._op_msg(
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\message.py", line 687, in _op_msg
    return _op_msg_uncompressed(flags, command, identifier, docs, opts)
bson.errors.InvalidDocument: cannot encode object: 24, of type: <class 'numpy.int64'>
ERROR:__main__:2022-11-16 15:36:46,774:cannot encode object: 29, of type: <class 'numpy.int64'>
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 114, in <module>
    strat_obj_dict[i].initialise()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 391, in initialise
    self._strat_status_record()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 134, in _strat_status_record
    self.stratRecorObj._add_one_doc(data_dict)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat_live_status_recorder.py", line 12, in _add_one_doc
    database.insert_dict("tradex_strat_data", f"strat{self.strategy_num}_{self.event_id}", data_dict)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\MongoClient.py", line 15, in insert_dict
    self.collection.insert_one(data_dictionary)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\collection.py", line 621, in insert_one
    self._insert_one(
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\collection.py", line 562, in _insert_one
    self.__database.client._retryable_write(acknowledged, _insert_command, session)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\mongo_client.py", line 1448, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\mongo_client.py", line 1321, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\_csot.py", line 105, in csot_wrapper
    return func(self, *args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\mongo_client.py", line 1362, in _retry_internal
    return func(session, sock_info, retryable)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\collection.py", line 550, in _insert_command
    result = sock_info.command(
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\pool.py", line 794, in command
    self._raise_connection_failure(error)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\pool.py", line 766, in command
    return command(
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\network.py", line 127, in command
    request_id, msg, size, max_doc_size = message._op_msg(
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\message.py", line 687, in _op_msg
    return _op_msg_uncompressed(flags, command, identifier, docs, opts)
bson.errors.InvalidDocument: cannot encode object: 29, of type: <class 'numpy.int64'>
ERROR:__main__:2022-11-16 15:39:18,617:cannot encode object: 78, of type: <class 'numpy.int64'>
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 114, in <module>
    strat_obj_dict[i].initialise()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 392, in initialise
    self._strat_status_record()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 135, in _strat_status_record
    self.stratRecorObj._add_one_doc(data_dict)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat_live_status_recorder.py", line 12, in _add_one_doc
    database.insert_dict("tradex_strat_data", f"strat{self.strategy_num}_{self.event_id}", data_dict)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\MongoClient.py", line 15, in insert_dict
    self.collection.insert_one(data_dictionary)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\collection.py", line 621, in insert_one
    self._insert_one(
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\collection.py", line 562, in _insert_one
    self.__database.client._retryable_write(acknowledged, _insert_command, session)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\mongo_client.py", line 1448, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\mongo_client.py", line 1321, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\_csot.py", line 105, in csot_wrapper
    return func(self, *args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\mongo_client.py", line 1362, in _retry_internal
    return func(session, sock_info, retryable)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\collection.py", line 550, in _insert_command
    result = sock_info.command(
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\pool.py", line 794, in command
    self._raise_connection_failure(error)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\pool.py", line 766, in command
    return command(
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\network.py", line 127, in command
    request_id, msg, size, max_doc_size = message._op_msg(
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pymongo\message.py", line 687, in _op_msg
    return _op_msg_uncompressed(flags, command, identifier, docs, opts)
bson.errors.InvalidDocument: cannot encode object: 78, of type: <class 'numpy.int64'>
ERROR:__main__:2022-11-16 22:24:46,963:local variable 'portfolio_dict' referenced before assignment
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 405, in update
    self._keep_a_check()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 347, in _keep_a_check
    self.__scalp_side("N", pausebuy=False)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 179, in __scalp_side
    self.order.cancel_all_pending_sell("N", "New sell order params")
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\order.py", line 99, in cancel_all_pending_sell
    df = get_event_holdings(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 33, in get_event_holdings
    port_dict = _get_portfolio_dict()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 30, in _get_portfolio_dict
    return portfolio_dict
UnboundLocalError: local variable 'portfolio_dict' referenced before assignment
