ERROR:__main__:2022-12-22 15:58:34,263:invalid literal for int() with base 10: '14440y'
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 104, in <module>
    eid_temp = int(input("Enter event id :"))
ValueError: invalid literal for int() with base 10: '14440y'
ERROR:__main__:2022-12-22 23:00:54,062:MaxAttempt(3) exhausted. User0
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 118, in tradex_caller
    response = req.post(url, data=body, headers=headers).json()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 128, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 709, in update
    self._keep_a_check()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 602, in _keep_a_check
    self.__scalp_side("N", trigger, pausebuy=False, pausesell=True)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 304, in __scalp_side
    self.__send_buy_orders(f"{trigger},ScalpingNo,{set_priceqty_message}", "N", temp_price, temp_qty)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 552, in __send_buy_orders
    self.order._buy(message, "N", price, qty)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\order.py", line 38, in _buy
    response = self.api_obj.tradex_caller(suffix, body)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 140, in tradex_caller
    raise Exception(f"MaxAttempt({retry_attempts}) exhausted. User{self.userid}")
Exception: MaxAttempt(3) exhausted. User0
ERROR:__main__:2022-12-22 23:01:40,333:MaxAttempt(3) exhausted. User0
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 118, in tradex_caller
    response = req.post(url, data=body, headers=headers).json()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 128, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 709, in update
    self._keep_a_check()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 604, in _keep_a_check
    self.__scalp_side("N", trigger, pausebuy=False, pausesell=False)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 304, in __scalp_side
    self.__send_buy_orders(f"{trigger},ScalpingNo,{set_priceqty_message}", "N", temp_price, temp_qty)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 552, in __send_buy_orders
    self.order._buy(message, "N", price, qty)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\order.py", line 38, in _buy
    response = self.api_obj.tradex_caller(suffix, body)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 140, in tradex_caller
    raise Exception(f"MaxAttempt({retry_attempts}) exhausted. User{self.userid}")
Exception: MaxAttempt(3) exhausted. User0
ERROR:__main__:2022-12-22 23:02:24,091:MaxAttempt(3) exhausted. User0
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 118, in tradex_caller
    response = req.post(url, data=body, headers=headers).json()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 128, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 709, in update
    self._keep_a_check()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 602, in _keep_a_check
    self.__scalp_side("N", trigger, pausebuy=False, pausesell=True)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 304, in __scalp_side
    self.__send_buy_orders(f"{trigger},ScalpingNo,{set_priceqty_message}", "N", temp_price, temp_qty)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 552, in __send_buy_orders
    self.order._buy(message, "N", price, qty)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\order.py", line 38, in _buy
    response = self.api_obj.tradex_caller(suffix, body)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 140, in tradex_caller
    raise Exception(f"MaxAttempt({retry_attempts}) exhausted. User{self.userid}")
Exception: MaxAttempt(3) exhausted. User0
ERROR:__main__:2022-12-22 23:03:08,564:MaxAttempt(3) exhausted. User0
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 118, in tradex_caller
    response = req.post(url, data=body, headers=headers).json()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 128, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 709, in update
    self._keep_a_check()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 604, in _keep_a_check
    self.__scalp_side("N", trigger, pausebuy=False, pausesell=False)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 304, in __scalp_side
    self.__send_buy_orders(f"{trigger},ScalpingNo,{set_priceqty_message}", "N", temp_price, temp_qty)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 552, in __send_buy_orders
    self.order._buy(message, "N", price, qty)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\order.py", line 38, in _buy
    response = self.api_obj.tradex_caller(suffix, body)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 140, in tradex_caller
    raise Exception(f"MaxAttempt({retry_attempts}) exhausted. User{self.userid}")
Exception: MaxAttempt(3) exhausted. User0
ERROR:__main__:2022-12-22 23:03:52,166:MaxAttempt(3) exhausted. User0
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 118, in tradex_caller
    response = req.post(url, data=body, headers=headers).json()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 128, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 709, in update
    self._keep_a_check()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 602, in _keep_a_check
    self.__scalp_side("N", trigger, pausebuy=False, pausesell=True)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 304, in __scalp_side
    self.__send_buy_orders(f"{trigger},ScalpingNo,{set_priceqty_message}", "N", temp_price, temp_qty)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 552, in __send_buy_orders
    self.order._buy(message, "N", price, qty)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\order.py", line 38, in _buy
    response = self.api_obj.tradex_caller(suffix, body)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 140, in tradex_caller
    raise Exception(f"MaxAttempt({retry_attempts}) exhausted. User{self.userid}")
Exception: MaxAttempt(3) exhausted. User0
