ERROR:__main__:2023-01-08 19:20:14,537:local variable 'portfolio_dict' referenced before assignment
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 128, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 789, in update
    self._keep_a_check()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 680, in _keep_a_check
    self.__scalp_side("Y", trigger, pausebuy=False, pausesell=False)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 271, in __scalp_side
    if (temp_qty > 0) and (temp_price <= self.stop_buy_upper_price) and (not self.order.is_same_order("Y", temp_price, temp_qty, "buy")) and (not self._is_myorder_best("Y")):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 434, in _is_myorder_best
    if (self.order.is_same_order(asset, best_price, best_qty, "buy")) and buying_at_competitive:
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\order.py", line 170, in is_same_order
    df = self.mybet.get_event_holdings(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 44, in get_event_holdings
    port_dict = self._get_portfolio_dict()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 41, in _get_portfolio_dict
    return portfolio_dict
UnboundLocalError: local variable 'portfolio_dict' referenced before assignment
ERROR:__main__:2023-01-08 23:00:56,304:MaxAttempt(3) exhausted. User0
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 118, in tradex_caller
    response = req.post(url, data=body, headers=headers).json()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 128, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 789, in update
    self._keep_a_check()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 680, in _keep_a_check
    self.__scalp_side("Y", trigger, pausebuy=False, pausesell=False)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 286, in __scalp_side
    self.__send_all_sell(f"{trigger},SellingBoughtQty,{set_priceqty_message}", "Y", sell_price, sell_qty)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 582, in __send_all_sell
    self.order._sell(message, "Y", sell_price, sell_qty)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\order.py", line 71, in _sell
    response = self.api_obj.tradex_caller(suffix, body)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 140, in tradex_caller
    raise Exception(f"MaxAttempt({retry_attempts}) exhausted. User{self.userid}")
Exception: MaxAttempt(3) exhausted. User0
ERROR:__main__:2023-01-08 23:02:27,774:MaxAttempt(3) exhausted. User0
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 118, in tradex_caller
    response = req.post(url, data=body, headers=headers).json()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 128, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 789, in update
    self._keep_a_check()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 630, in _keep_a_check
    self.__scalp_side("N", trigger, pausebuy=False, pausesell=False)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 305, in __scalp_side
    self.order.cancel_all_pending_buy("N", f"{trigger},NewBuyParams")
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\order.py", line 164, in cancel_all_pending_buy
    self._cancel_buy(message=message,
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\order.py", line 103, in _cancel_buy
    response = self.api_obj.tradex_caller(suffix, body)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 140, in tradex_caller
    raise Exception(f"MaxAttempt({retry_attempts}) exhausted. User{self.userid}")
Exception: MaxAttempt(3) exhausted. User0
ERROR:__main__:2023-01-08 23:03:21,219:MaxAttempt(3) exhausted. User0
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 118, in tradex_caller
    response = req.post(url, data=body, headers=headers).json()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 128, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 789, in update
    self._keep_a_check()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 692, in _keep_a_check
    self.__scalp_side("N", trigger, pausebuy=False, pausesell=False)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 305, in __scalp_side
    self.order.cancel_all_pending_buy("N", f"{trigger},NewBuyParams")
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\order.py", line 164, in cancel_all_pending_buy
    self._cancel_buy(message=message,
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\order.py", line 103, in _cancel_buy
    response = self.api_obj.tradex_caller(suffix, body)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 140, in tradex_caller
    raise Exception(f"MaxAttempt({retry_attempts}) exhausted. User{self.userid}")
Exception: MaxAttempt(3) exhausted. User0
ERROR:__main__:2023-01-08 23:04:15,090:MaxAttempt(3) exhausted. User0
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 118, in tradex_caller
    response = req.post(url, data=body, headers=headers).json()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 128, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 789, in update
    self._keep_a_check()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 690, in _keep_a_check
    self.__scalp_side("N", trigger, pausebuy=False, pausesell=True)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 305, in __scalp_side
    self.order.cancel_all_pending_buy("N", f"{trigger},NewBuyParams")
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\order.py", line 164, in cancel_all_pending_buy
    self._cancel_buy(message=message,
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\order.py", line 103, in _cancel_buy
    response = self.api_obj.tradex_caller(suffix, body)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 140, in tradex_caller
    raise Exception(f"MaxAttempt({retry_attempts}) exhausted. User{self.userid}")
Exception: MaxAttempt(3) exhausted. User0
ERROR:__main__:2023-01-08 23:05:11,553:MaxAttempt(3) exhausted. User0
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 118, in tradex_caller
    response = req.post(url, data=body, headers=headers).json()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 128, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 789, in update
    self._keep_a_check()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 690, in _keep_a_check
    self.__scalp_side("N", trigger, pausebuy=False, pausesell=True)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 305, in __scalp_side
    self.order.cancel_all_pending_buy("N", f"{trigger},NewBuyParams")
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\order.py", line 164, in cancel_all_pending_buy
    self._cancel_buy(message=message,
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\order.py", line 103, in _cancel_buy
    response = self.api_obj.tradex_caller(suffix, body)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 140, in tradex_caller
    raise Exception(f"MaxAttempt({retry_attempts}) exhausted. User{self.userid}")
Exception: MaxAttempt(3) exhausted. User0
ERROR:__main__:2023-01-09 11:52:56,552:'title'
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 116, in <module>
    if "Bitcoin USDT will stay above" in data_dict["title"]:
KeyError: 'title'
