ERROR:__main__:2022-11-07 15:22:49,015:'title'
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 114, in <module>
    strat_obj_dict[i].initialise()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 294, in initialise
    self.priceatri.initialise_priceatri()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\price_attributes.py", line 78, in initialise_priceatri
    self.initialise_event()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\event_params.py", line 18, in initialise_event
    self.title = static_data["title"]
KeyError: 'title'
ERROR:__main__:2022-11-07 15:22:49,144:fromisoformat: argument must be str
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 123, in <module>
    while dt.datetime.now() <= dt.datetime.fromisoformat(strat_obj_dict[i].priceatri.ends_at):
TypeError: fromisoformat: argument must be str
ERROR:__main__:2022-11-07 15:23:32,326:MaxAttempt(3) exhausted
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 31, in tradex_caller
    response = req.post(url, data=body, headers=headers).json()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 114, in <module>
    strat_obj_dict[i].initialise()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 294, in initialise
    self.priceatri.initialise_priceatri()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\price_attributes.py", line 78, in initialise_priceatri
    self.initialise_event()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\event_params.py", line 23, in initialise_event
    self.last_executed_trades = clean_lastTradesInfo_df(self.eid)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\lasttradesinfo.py", line 46, in clean_lastTradesInfo_df
    df = _get_lastTradesInfo_df(id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\lasttradesinfo.py", line 15, in _get_lastTradesInfo_df
    resp = tradex_caller("lastTradesInfo", body={"probeid": id})
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 49, in tradex_caller
    raise Exception(f"MaxAttempt({retry_attempts}) exhausted")
Exception: MaxAttempt(3) exhausted
ERROR:__main__:2022-11-07 15:23:37,530:invalid literal for int() with base 10: 'ove 20'
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 114, in <module>
    strat_obj_dict[i].initialise()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 297, in initialise
    self.__set_strike_price()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 66, in __set_strike_price
    self.strike_price = int(self.priceatri.title[25:31])
ValueError: invalid literal for int() with base 10: 'ove 20'
ERROR:__main__:2022-11-07 15:23:47,531:invalid literal for int() with base 10: 'ove 20'
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 114, in <module>
    strat_obj_dict[i].initialise()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 297, in initialise
    self.__set_strike_price()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 66, in __set_strike_price
    self.strike_price = int(self.priceatri.title[25:31])
ValueError: invalid literal for int() with base 10: 'ove 20'
ERROR:__main__:2022-11-07 15:23:56,106:MaxAttempt(3) exhausted
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 31, in tradex_caller
    response = req.post(url, data=body, headers=headers).json()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 114, in <module>
    strat_obj_dict[i].initialise()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 294, in initialise
    self.priceatri.initialise_priceatri()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\price_attributes.py", line 78, in initialise_priceatri
    self.initialise_event()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\event_params.py", line 23, in initialise_event
    self.last_executed_trades = clean_lastTradesInfo_df(self.eid)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\lasttradesinfo.py", line 46, in clean_lastTradesInfo_df
    df = _get_lastTradesInfo_df(id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\lasttradesinfo.py", line 15, in _get_lastTradesInfo_df
    resp = tradex_caller("lastTradesInfo", body={"probeid": id})
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\api_caller.py", line 49, in tradex_caller
    raise Exception(f"MaxAttempt({retry_attempts}) exhausted")
Exception: MaxAttempt(3) exhausted
ERROR:__main__:2022-11-07 15:28:35,666:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 114, in <module>
    strat_obj_dict[i].initialise()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 302, in initialise
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    df = get_event_holdings(id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    port_dict = _get_portfolio_dict()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    df = df.set_index("id")[["calls", 'summary']]
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:28:37,759:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 114, in <module>
    strat_obj_dict[i].initialise()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 302, in initialise
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    df = get_event_holdings(id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    port_dict = _get_portfolio_dict()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    df = df.set_index("id")[["calls", 'summary']]
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:28:39,468:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 114, in <module>
    strat_obj_dict[i].initialise()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 302, in initialise
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    df = get_event_holdings(id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    port_dict = _get_portfolio_dict()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    df = df.set_index("id")[["calls", 'summary']]
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:28:40,906:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 114, in <module>
    strat_obj_dict[i].initialise()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 302, in initialise
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    df = get_event_holdings(id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    port_dict = _get_portfolio_dict()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    df = df.set_index("id")[["calls", 'summary']]
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:28:42,000:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    df = get_event_holdings(id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    port_dict = _get_portfolio_dict()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    df = df.set_index("id")[["calls", 'summary']]
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:28:43,135:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    df = get_event_holdings(id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    port_dict = _get_portfolio_dict()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    df = df.set_index("id")[["calls", 'summary']]
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:28:44,298:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    df = get_event_holdings(id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    port_dict = _get_portfolio_dict()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    df = df.set_index("id")[["calls", 'summary']]
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:28:45,319:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    df = get_event_holdings(id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    port_dict = _get_portfolio_dict()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    df = df.set_index("id")[["calls", 'summary']]
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:29:46,478:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    df = get_event_holdings(id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    port_dict = _get_portfolio_dict()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    df = df.set_index("id")[["calls", 'summary']]
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:29:47,782:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    df = get_event_holdings(id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    port_dict = _get_portfolio_dict()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    df = df.set_index("id")[["calls", 'summary']]
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:29:48,926:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    df = get_event_holdings(id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    port_dict = _get_portfolio_dict()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    df = df.set_index("id")[["calls", 'summary']]
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:29:50,258:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    df = get_event_holdings(id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    port_dict = _get_portfolio_dict()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    df = df.set_index("id")[["calls", 'summary']]
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:30:51,791:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    df = get_event_holdings(id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    port_dict = _get_portfolio_dict()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    df = df.set_index("id")[["calls", 'summary']]
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:30:52,847:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    df = get_event_holdings(id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    port_dict = _get_portfolio_dict()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    df = df.set_index("id")[["calls", 'summary']]
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:30:53,779:'>' not supported between instances of 'float' and 'NoneType'
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 315, in update
    self._get_situation()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 183, in _get_situation
    elif (99 - self.yes_fair_price) > self.priceatri.no_best_price:
TypeError: '>' not supported between instances of 'float' and 'NoneType'
ERROR:__main__:2022-11-07 15:30:54,812:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    df = get_event_holdings(id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    port_dict = _get_portfolio_dict()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    df = df.set_index("id")[["calls", 'summary']]
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:31:56,320:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    df = get_event_holdings(id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    port_dict = _get_portfolio_dict()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    df = df.set_index("id")[["calls", 'summary']]
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:31:57,354:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    df = get_event_holdings(id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    port_dict = _get_portfolio_dict()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    df = df.set_index("id")[["calls", 'summary']]
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:31:58,754:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    df = get_event_holdings(id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    port_dict = _get_portfolio_dict()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    df = df.set_index("id")[["calls", 'summary']]
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:31:59,967:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    df = get_event_holdings(id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    port_dict = _get_portfolio_dict()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    df = df.set_index("id")[["calls", 'summary']]
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:33:01,885:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    df = get_event_holdings(id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    port_dict = _get_portfolio_dict()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    df = df.set_index("id")[["calls", 'summary']]
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:33:03,077:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    df = get_event_holdings(id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    port_dict = _get_portfolio_dict()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    df = df.set_index("id")[["calls", 'summary']]
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:33:04,512:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    df = get_event_holdings(id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    port_dict = _get_portfolio_dict()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    df = df.set_index("id")[["calls", 'summary']]
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:33:06,098:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    def get_holding_qty(id):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    def get_event_holdings(id):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    else:
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:34:07,206:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    def get_holding_qty(id):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    def get_event_holdings(id):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    else:
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:34:08,205:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    def get_holding_qty(id):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    def get_event_holdings(id):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    else:
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:34:09,363:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    def get_holding_qty(id):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    def get_event_holdings(id):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    else:
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:34:10,399:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    def get_holding_qty(id):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    def get_event_holdings(id):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    else:
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:35:12,130:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    def get_holding_qty(id):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    def get_event_holdings(id):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    else:
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:35:13,314:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    def get_holding_qty(id):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    def get_event_holdings(id):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    else:
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:35:14,451:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    def get_holding_qty(id):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    def get_event_holdings(id):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    else:
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:35:17,544:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    def get_holding_qty(id):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    def get_event_holdings(id):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    else:
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:36:18,905:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    event_holdings_df.reset_index(inplace=True)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    portfolio_dict = {}
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    else:
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:36:19,961:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    event_holdings_df.reset_index(inplace=True)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    portfolio_dict = {}
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    else:
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:36:21,018:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    event_holdings_df.reset_index(inplace=True)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    portfolio_dict = {}
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    else:
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:36:22,151:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    event_holdings_df.reset_index(inplace=True)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    portfolio_dict = {}
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    else:
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:37:23,432:"None of ['id'] are in the columns"
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 316, in update
    self._set_qty()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 188, in _set_qty
    self.holding_yes_qty, self.holding_no_qty = get_holding_qty(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 54, in get_holding_qty
    event_holdings_df.reset_index(inplace=True)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 28, in get_event_holdings
    portfolio_dict = {}
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 23, in _get_portfolio_dict
    else:
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\venv\lib\site-packages\pandas\core\frame.py", line 5503, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['id'] are in the columns"
ERROR:__main__:2022-11-07 15:56:04,082:local variable 'portfolio_dict' referenced before assignment
Traceback (most recent call last):
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\main_strategy_run.py", line 127, in <module>
    strat_obj_dict[j].update()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 318, in update
    self._keep_a_check()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 288, in _keep_a_check
    self.__scalp_side("Y")
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\strat7.py", line 127, in __scalp_side
    self.order.cancel_all_pending_sell("Y", "New sell order params")
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\order.py", line 99, in cancel_all_pending_sell
    df = get_event_holdings(self.event_id)
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 32, in get_event_holdings
    port_dict = _get_portfolio_dict()
  File "D:\Synced folder 2\tradex_opinionTrading\codes_2\mybets.py", line 29, in _get_portfolio_dict
    return portfolio_dict
UnboundLocalError: local variable 'portfolio_dict' referenced before assignment
